#!/usr/bin/env bash

echo 'Path to bash'
echo $BASH

echo 'BASH ENVIRONMENT'
echo $BASH_ENV

echo 'BASH SUBSHELL'
echo $BASH_SUBSHELL

echo 'BASH PID'
echo $BASHPID
echo $$

echo 'BASH PROCESS LISTING'
ps ax | grep bash

echo 'BASH SUBSHELL'

echo "\$\$ outside of subshell = $$"                              # 9602
echo "\$BASH_SUBSHELL  outside of subshell = $BASH_SUBSHELL"      # 0
echo "\$BASHPID outside of subshell = $BASHPID"                   # 9602

echo

( echo "\$\$ inside of subshell = $$"                             # 9602
  echo "\$BASH_SUBSHELL inside of subshell = $BASH_SUBSHELL"      # 1
  echo "\$BASHPID inside of subshell = $BASHPID" )                # 9603
  # Note that $$ returns PID of parent process.

echo 'BASH VERSION INFO:'

for n in 0 1 2 3 4 5
do
  echo "BASH_VERSINFO[$n] = ${BASH_VERSINFO[$n]}"
done  

echo 'BASH VERSION:'

echo "BASH VERSION = $BASH_VERSION"

echo 'CDPATH'

echo $CDPATH

echo 'DIRSTACK'

echo $DIRSTACK

echo 'EDITOR'

echo $EDITOR

echo 'EUID'

echo $EUID

echo 'FUNCNAME'

echo $FUNCNAME

echo 'GLOBIGNORE'

echo $GLOBIGNORE

echo 'GROUPS'

echo $GROUPS




