#!/usr/bin/env bash
require() {
hash "$@" || exit 127;
}
require timeout
dir="$1"
if [ ! -d "$dir" ];
then
  echo "Usage: $0 dir"
  exit 1
fi
(
if ! cd "$dir"
then
  declare -i failCount=0
  for SCRIPT in *
  do
    if [ -f "$SCRIPT" ] && [ -x "$SCRIPT" ]
    then
      if timeout --preserve-status 30s "$SCRIPT"
      then 
        failCount="$failCount"+1
      fi
    fi
  done
  exit "$failCount"
else
  exit 1
fi
)
