#!/usr/bin/env bash
echo "curl -s -o tutorial.json 'https://api.github.com/repos/stedolan/jq/commits?per_page=5'"
echo
if [[ ! -e "tutorial.json" ]]
then
  curl -s -o tutorial.json 'https://api.github.com/repos/stedolan/jq/commits?per_page=5'
fi
echo
echo "cat tutorial.json | jq '.'"
cat tutorial.json | jq '.'
echo
echo "cat tutorial.json | jq '.[0]"
echo
cat tutorial.json | jq '.[0]'
echo
echo "cat tutorial.json | jq '.[0] | {message: .commit.message, name: .commit.committer.name}'"
echo
cat tutorial.json | jq '.[0] | {message: .commit.message, name: .commit.committer.name}'
echo
echo "cat tutorial.json | jq '[.[] | {message: .commit.message, name: .commit.committer.name, parents: [.parents[].html_url]}]'" 
echo
cat tutorial.json | jq '[.[] | {message: .commit.message, name: .commit.committer.name, parents: [.parents[].html_url]}]'
echo
printf "echo '{\"fruit\":{\"name\":\"apple\",\"color\":\"green\",\"price\":1.20}}' | jq '.'\n"
echo '{"fruit":{"name":"apple","color":"green","price":1.20}}' | jq '.'
printf "echo '{\"fruit\":{\"name\":\"apple\",\"color\":\"green\",\"price\":1.20}}' > fruit.json\n"
if [[ ! -e "fruit.json" ]]
then
  echo '{"fruit":{"name":"apple","color":"green","price":1.20}}' > fruit.json
fi
echo "jq . fruit.json"
echo
jq . fruit.json
echo
echo "curl -s http://api.open-notify.org/iss-now.json | jq '.'"
echo
curl -s http://api.open-notify.org/iss-now.json | jq '.'
echo
echo "cat fruit.json | jq .fruit"
echo
cat fruit.json | jq .fruit
echo
echo "jq '.fruit.color' fruit.json"
echo
jq '.fruit.color' fruit.json
echo
echo "jq '.fruit.color,.fruit.price' fruit.json"
jq '.fruit.color,.fruit.price' fruit.json
echo
printf "echo '{ \"with space\": \"hello\" }' | jq '.\"with space\"'\n"
echo '{ "with space": "hello" }' | jq '."with space"'
echo
printf "echo '[\"x\",\"y\",\"z\"]' | jq '.[]'\n"
echo
echo '["x","y","z"]' | jq '.[]'
echo
