#!/usr/bin/env bash
MAX=$((2**8))
COUNT=$((COUNT + 5 + MAX * 2))
echo $COUNT
let COUNT+=5+MAX*2
echo $COUNT
Y=20
echo $(( X+=5 , Y*=3 ))
let X+=5 Y*=3
echo $Y

let Y=(X+2)*10
echo $Y
Y=$(( ( X + 2 ) * 10 ))
echo $Y
