#!/usr/bin/env bash
# Source: https://github.com/jasonc/scripts/blob/master/ping-host
# Usage: ping-host HOST [HOSTN]...
# Returns 0 if the hosts respond to ping or 1 if any of them fail to respond.
#
# Supported operating systems: Linux, Mac.

# Help
if [ -z "$1" ] || [ "$1" = '-h' ] || [ "$1" = '--help' ]; then
  echo 'Usage: ping-host HOST [HOSTN]...' >&2
  echo 'Returns 0 if the hosts respond to ping or 1 if any of them fail to respond.' >&2
  exit
fi

# What OS are we on?
OS=$(uname -s)

if [[ "$OS" == 'Linux' || "$OS" == 'Mac' ]]; then
  # Linux / Mac
  PING='ping -c 1 -W 1 -q'
  PING_SUFFIX_ARGS=""
fi

# Hope for the best, prepare for the worst.
RETURN_CODE=0

# Loop through the hosts provided on the command line.
for HOST in "$@"; do

  if ! eval "$PING $HOST $PING_SUFFIX_ARGS"; then
    RETURN_CODE=1
    echo "$HOST down"
  fi
done

exit $RETURN_CODE
