#!/usr/bin/env bash
PS3="Select the operation: "

select opt in add subtract multiply divide quit; do

  case $opt in
  add)
    read -r -p "Enter the first number: " n1
    read -r -p "Enter the second number: " n2
    echo "$n1 + $n2 = $((n1 + n2))"
    ;;
  subtract)
    read -r -p "Enter the first number: " n1
    read -r -p "Enter the second number: " n2
    echo "$n1 - $n2 = $((n1 - n2))"
    ;;
  multiply)
    read -r -p "Enter the first number: " n1
    read -r -p "Enter the second number: " n2
    echo "$n1 * $n2 = $((n1 * n2))"
    ;;
  divide)
    read -r -p "Enter the first number: " n1
    read -r -p "Enter the second number: " n2
    echo "$n1 / $n2 = $((n1 / n2))"
    ;;
  quit)
    break
    ;;
  *)
    echo "Invalid option $REPLY"
    ;;
  esac
done
