#!/usr/bin/env bash
# Instructions: 
# Place this script in /tmp
# Description: 
# This script simulates a service or a daemon.
PID_FILE="/tmp/sleep-walking-server.pid" 
trap "rm $PID_FILE; exit 1;" SIGHUP SIGINT SIGTERM 
echo "$$" > $PID_FILE 
while true 
do 
:
done
