#!/usr/bin/env bash
# Instructions:
# Place this script in /tmp
# Description:
# This script simulates a service or a daemon.
removepid() {
  PID_FILE="/tmp/sleep-walking-server.pid"
  rm "$PID_FILE"
  exit 1
}
trap removepid SIGHUP SIGINT SIGTERM
echo "$$" >"$PID_FILE"
while true; do
  :
done
