#!/usr/bin/env bash
touch testfile.tst
FILE="testfile.tst"
if [ -r $FILE ] && [ -w $FILE ]; then
  echo "testfile is rw"
fi
FN="$FILE"
if [ -r "$FN" ]; then
  if [ -f "$FN" ] || [ -p "$FN" ]; then
    echo "testfile is r"
  fi
fi
if [ -z "$V1" ] || [ -z "${V2:=YIKES}" ]; then
  echo "$V2"
fi
