#!/usr/bin/env bash
seq 6 | sed 'n;n;s/./x/'
printf "\n-------------------\n"
seq 6 | sed '0~3s/./x/'
printf "\n-------------------\n"
seq 3 | sed -n '2{s/2/X/ ; p}'
printf "\n-------------------\n"
echo "hello world" | sed 'y/abcdefghij/0123456789/'
printf "\n-------------------\n"
seq 3 | sed '2a hello'
printf "\n-------------------\n"
seq 3 | sed '2a\
hello'
printf "\n-------------------\n"
seq 3 | sed '2a\
hello\
world
3s/./X/'
printf "\n-------------------\n"
sed -e "2a\\" -e hello <(seq 3)
printf "\n-------------------\n"
read -r
printf '%s\n' "aaa bbb ccc" | sed '='
printf "\n-------------------\n"
seq 3 | sed -e "2c\\" -e hello
printf "\n-------------------\n"
seq 3 | sed '2c\
hello
s/./X/'
printf "\n-------------------\n"
seq 5 | sed '2,4c\
hello\
world'
printf "\n-------------------\n"
seq 10 | sed '2,9c hello'
printf "\n-------------------\n"
seq 6 | sed '1d
3d
5d'
printf "\n-------------------\n"
seq 6 | sed -e 1d -e 3d -e 5d
printf "\n-------------------\n"
seq 6 | sed '1d;3d;5d'
printf "\n-------------------\n"
seq 4 | sed '{1d;3d}'
printf "\n-------------------\n"
seq 6 | sed '{1d;3d};5d'
printf "\n-------------------\n"
seq 3 | sed '/1/b x ; s/^/=/ ; :x ; 3d'
printf "\n-------------------\n"
seq 2 | sed '1aHello ; 2d'
printf "\n-------------------\n"
seq 2 | sed -e 1aHello -e 2d
printf "\n-------------------\n"
seq 2 | sed '1aHello
2d'
printf "\n-------------------\n"
seq 2 | sed '1a\
Hello
2d'
printf "\n-------------------\n"
seq 2 | sed '1w hello.txt ; 2d'
ls -log ./*hello*
cat 'hello.txt ; 2d'
rm -f 'hello.txt ; 2d'
echo x | sed '1rhello.txt ; N'
printf "\n-------------------\n"
echo a | sed '1e touch foo#bar'
ls -1 foo#*
echo a | sed '1e touch foo ; s/a/b/'
printf "\n-------------------\n"
echo a | sed 's/a/b/w1.txt#foo'
ls -1 1.txt#*
