#!/usr/bin/env bash
printf "grep -e '^  *.*' lines.txt\n"
grep -e '^  *.*' lines.txt
printf "grep -e 'A.E' lines.txt\n"
grep -e 'A.E' lines.txt
printf "grep -e 'A.*E' lines.txt\n"
grep -e 'A.*E' lines.txt
printf "grep -e '\.   ' lines.txt\n"
grep -e '\.   ' lines.txt
printf "grep -e '80.86' lines.txt\n"
grep -e '80.86' lines.txt
printf "grep -e 'Chapter.' lines.txt\n"
grep -e 'Chapter.' lines.txt
printf "grep -e '[Ww]hat' lines.txt\n"
grep -e '[Ww]hat' lines.txt
printf "grep -e '\.H[123]' lines.txt\n"
grep -e '\.H[123]' lines.txt
printf "grep -e '.[!?;:,\".] .' lines.txt\n"
grep -e '.[!?;:,".] .' lines.txt
printf "awk '/[a\]1]/ { print }' lines.txt\n"
awk '/[a\]1]/ { print }' lines.txt
printf "grep -e '[]a1]' lines.txt\n"
grep -e '[]a1]' lines.txt
printf "grep -e '[][ a-z]' lines.txt\n"
grep -e '[][ a-z]' lines.txt
printf "awk '/[[\] a-z]/ { print }' lines.txt\n"
awk '/[[\[ a-z]/ { print }' lines.txt
printf "grep -e '[A-Z]' lines.txt\n"
grep -e '[A-Z]' lines.txt
printf "grep -e '[0-9]' lines.txt\n"
grep -e '[0-9]' lines.txt
printf "grep -e '[cC]hapter [1-9]' lines.txt\n"
grep -e '[cC]hapter [1-9]' lines.txt
grep -e '[0-9a-z?,.;:’"]' lines.txt
printf "grep -e \"[0-9a-z?,.;:'\"]\" lines.txt\n"
grep -e "[0-9a-z?,.;:'\"]" lines.txt
printf "grep -e '[a-zA-Z][.?!]' lines.txt\n"
grep -e '[a-zA-Z][.?!]' lines.txt
printf "grep -e '[0-1][0-9][-/][0-3][0-9][-/][0-9][0-9]' lines.txt\n"
grep -e '[0-1][0-9][-/][0-3][0-9][-/][0-9][0-9]' lines.txt
printf "grep -e '[^0-9]' lines.txt\n"
grep -e '[^0-9]' lines.txt
