#!/usr/bin/env bash
sed -n '/hello/p' hello.txt
printf "%s\n" abode bad bed bit bid byte body | sed -n '/^b.d/p'
printf "\n---------------\n"
echo 'a+b=c' > foo
sed -n '/a+b/p' foo
printf "\n---------------\n"
echo 'a+b=c' > foo
sed -E -n '/a\+b/p' foo
printf "\n---------------\n"
echo aab > foo
sed -n '/a\+b/p' foo
printf "\n---------------\n"
echo aab > foo
sed -E -n '/a+b/p' foo
printf "\n---------------\n"
echo "abcdef abcdef" | sed 's/abcdef/\U&/g'
printf "\n---------------\n"
echo "bab" | sed 's/a*b/\
&/g' | sed '1d'
printf "\n---------------\n"
echo "bab" | sed 's/a\?b/\
&/g' | sed '1d'
printf "\n---------------\n"
echo "abaaaababbbbbaaaaaabbbbbbb" \
  | sed 's/a\+b/\
&/g' | sed '1d'
echo "abaaaababbbbbaaaaaabbbbbbb" \
  | sed -n 's/.*/&/p'
echo  \
  | sed -n 's/.*/&/p'
echo "main(int argc, char* argv)" \
  | sed -n 's/^main.*(.*)/&/p'
echo "#main(int argc, char* argv)" \
  | sed -n 's/^#/&/p'
echo "https://google.com/index/" \
  | sed -n 's/\/$/&/p'
echo "https://google.com/index/" \
  | sed 's/[a-zA-Z0-9]/\
&/g' | sed '1d'
