#!/usr/bin/env bash
printf "sed 's/Massachusetts/MA/' list.txt\n"
sed 's/Massachusetts/MA/' list.txt
printf "sed -e 's/Massachusetts/MA/' -e 's/Pennsylvania/PA/' \
  -e 's/California/CA/' -e 's/Virginia/VA/' \
  -e 's/Oklahoma/OK/' list.txt\n"
sed -e 's/Massachusetts/MA/' -e 's/Pennsylvania/PA/' \
  -e 's/California/CA/' -e 's/Virginia/VA/' \
  -e 's/Oklahoma/OK/' list.txt
printf "sed -e 's/Massachusetts/MA/' -e 's/Pennsylvania/PA/' \
  -e 's/California/CA/' -e 's/Virginia/VA/' \
  -e 's/Oklahoma/OK/' list.txt \
  | sed -f sedscr\n"
sed -e 's/Massachusetts/MA/' -e 's/Pennsylvania/PA/' \
  -e 's/California/CA/' -e 's/Virginia/VA/' \
  -e 's/Oklahoma/OK/' list.txt \
  | sed -f sedscr
printf "sed -n 's/Massachusetts/MA/p' list.txt\n"
sed -n 's/Massachusetts/MA/p' list.txt
printf "awk '{ print \$1 }' list.txt\n"
awk '{ print $1 }' list.txt
printf "awk '/Massachusetts/' list.txt\n"
awk '/Massachusetts/' list.txt
printf "awk '/Massachusetts/ {print \$1 }' list.txt\n"
awk '/Massachusetts/ {print $1 }' list.txt
printf "awk -F, '/Massachusetts/ {print \$1 }' list.txt\n"
awk -F, '/Massachusetts/ {print $1 }' list.txt
printf "awk -F, '{ print \$1; print \$2; print \$3 }' list.txt\n"
awk -F, '{ print $1; print $2; print $3 }' list.txt
printf "sed -f namestate list.txt | awk -F, '{ print \$4 }' | sort | uniq \n"
sed -f namestate list.txt | awk -F, '{ print $4 }' | sort | uniq
