#!/usr/bin/env bash
printf "awk '{
if (\$1 > max)
max = \$1
arr[\$1] = \$0
}
END {
for (x = 1; x <= max; x++)
if (x in arr)
print arr[x]
}' numlines.txt\n"
awk '{
if ($1 > max)
max = $1
arr[$1] = $0
}
END {
for (x = 1; x <= max; x++)
if (x in arr)
print arr[x]
}' numlines.txt
awk '# Record a 1 for each word that is used at least once.
{
for (i = 1; i <= NF; i++)
used[$i] = 1
}
# Find number of distinct words more than 10 characters long.
END {
for (x in used)
if (length(x) > 10) {
++num_long_words
print x
}
print num_long_words, "words longer than 10 characters"
}' french.txt
