#!/usr/bin/env bash
awk 'length($1) > 5 {print}' mywords.txt
awk '$1 ~ /^[b,c]/ {print $1}' mywords.txt
awk 'NR % 2 == 0 {print}' mywords.txt
awk '{print NR, $0}' mywords.txt
awk '{print substr($0, 4)}' source.c > dest.c
awk 'END {print NR}' mywords.txt mywords2.txt
awk 'BEGIN {srand()} {lines[NR] = $0} END { r=int(rand()*NR + 1); print lines[r]}' mywords.txt mywords2.txt
awk 'match($0, /^[c,b]/)' mywords.txt mywords2.txt
awk 'match($0, /i/) {print $0 " has i character at " RSTART}' mywords.txt mywords2.txt
awk 'BEGIN { print ARGC, ARGV[0], ARGV[1], ARGV[2]}' mywords.txt mywords2.txt
awk -f stats.awk values.txt
