#!/usr/bin/env bash
function usage() {
  echo "Usage: $0 couponcount" >&2
  exit 1
}
re='^[0-9]+$'
if ! [[ "$1" =~ $re ]]; then
  echo "Not a number" >&2
  usage
fi
declare -i nocoupons="$1"
awk "BEGIN {  
s=\"abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789\" 
srand()  
for (i=1;i<=${nocoupons};i++) { 
code=\"\" 
for (j=1;j<=8;j++) 
  code = code\"\"substr(s,int(rand()*62)+1,1) 
print code 
} 
}"
