#!/usr/bin/env bash
printf "awk '
function myprint(num)
{
printf \"%%6.3g\n\", num
}
\$3 > 0 { myprint(\$3) }' fields.txt\n"
awk '
function myprint(num)
{
printf "%6.3g\n", num
}
$3 > 0 { myprint($3) }' fields.txt
printf "awk 'function rev (str, len) {
if (len == 0) {
return
}
printf \"%%c\", substr(str, len, 1)
rev(str, len - 1)
}
BEGIN {print rev(\"hello\", 5)}'\n"
awk 'function rev (str, len) {
if (len == 0) {
return
}
printf "%c", substr(str, len, 1)
rev(str, len - 1)
}
BEGIN {print rev("hello", 5)}'
printf "awk 'function changeit (array, ind, nvalue) {
array[ind] = nvalue
}
BEGIN {
a[1] = 1 ; a[2] = 2 ; a[3] = 3
changeit(a, 2, \"two\")
printf \"a[1] = %%s, a[2] = %%s, a[3] = %%s\n\", a[1], a[2], a[3]
}'\n"
awk 'function changeit (array, ind, nvalue) {
array[ind] = nvalue
}
BEGIN {
a[1] = 1 ; a[2] = 2 ; a[3] = 3
changeit(a, 2, "two")
printf "a[1] = %s, a[2] = %s, a[3] = %s\n", a[1], a[2], a[3]
}'
printf "awk '
function maxelt (vec, i, ret) {
for (i in vec) {
if (ret == \"\" || vec[i] > ret)
ret = vec[i]
}
return ret
}
# Load all fields of each record into nums.
{
for(i = 1; i <= NF; i++)
nums[NR, i] = \$i
}
END {
print maxelt(nums)
}' maxnums.txt\n"
awk '
function maxelt (vec, i, ret) {
for (i in vec) {
if (ret == "" || vec[i] > ret)
ret = vec[i]
}
return ret
}
# Load all fields of each record into nums.
{
for(i = 1; i <= NF; i++)
nums[NR, i] = $i
}
END {
print maxelt(nums)
}' maxnums.txt
