#!/usr/bin/env bash
printf "awk '{ if (NF > max) max = NF }
END { print max }' inventory.txt\n"
awk '{ if (NF > max) max = NF }
END { print max }' inventory.txt
printf "awk 'length(\$0) > 30' BBS.txt\n"
awk 'length($0) > 30' BBS.txt
printf "awk 'NF > 0' BBS.txt\n"
awk 'NF > 0' BBS.txt
printf "awk '{ if (NF > 0) print }' BBS.txt\n"
awk '{ if (NF > 0) print }' BBS.txt
printf "awk 'BEGIN { srand(); for (i = 1; i <= 7; i++)
print int(101 * rand()) }'\n"
awk 'BEGIN { srand(); for (i = 1; i <= 7; i++)
print int(101 * rand()) }'
printf "ls -l | awk '{ x += \$5 } ; END { print \"total bytes: \" x }'\n"
# shellcheck disable=SC2012
ls -l | awk '{ x += $5 } ; END { print "total bytes: " x }'
printf "expand program.java | awk '{ if (x < length()) x = length() } \
END { print \"maximum line length is \" x }'\n"
expand program.java | awk '{ if (x < length()) x = length() }
END { print "maximum line length is " x }'
printf "awk '{ nlines++ } \
END { print nlines }' BBS.txt\n"
awk '{ nlines++ }
END { print nlines }' BBS.txt
printf "awk 'END { print NR }' BBS.txt\n"
awk 'END { print NR }' BBS.txt
printf "awk '{ print NR, \$0 }' BBS.txt\n"
awk '{ print NR, $0 }' BBS.txt
