#!/usr/bin/env bash
echo "awk '/foo/ { print "'$2'" }' BBS.txt"
awk '/foo/ { print $2 }' BBS.txt
echo "awk '"'$1'" ~ /J/' inventory.txt"
awk '$1 ~ /J/' inventory.txt
echo "awk '{ if ("'$1'" ~ /J/) print }' inventory.txt"
awk '{ if ($1 ~ /J/) print }' inventory.txt
echo "awk '"'$1'" !~ /J/' inventory.txt"
awk '$1 !~ /J/' inventory.txt
echo "awk 'tolower("'$1'") ~ /foo/ { print }' BBS.txt"
awk 'tolower($1) ~ /foo/ { print }' BBS.txt
echo "awk '"'$1'" == "'"foo"'" { print "'$2'" }' BBS.txt"
awk '$1 == "foo" { print $2 }' BBS.txt
echo "awk '"'$1'" ~ "'"foo"'" { print "'$2'" }' BBS.txt"
awk '$1 ~ "foo" { print $2 }' BBS.txt
echo "awk '"'$1'" ~ /foo/ { print "'$2'" }' BBS.txt"
awk '$1 ~ /foo/ { print $2 }' BBS.txt
echo "awk '/2400/ && /foo/' BBS.txt"
awk '/2400/ && /foo/' BBS.txt
echo "awk '/2400/ || /foo/' BBS.txt"
awk '/2400/ || /foo/' BBS.txt
echo "awk '! /foo/' BBS.txt"
awk '! /foo/' BBS.txt
echo "awk 'BEGIN { print "'"Analysis of '"'foo'"'"'" } \
/foo/ { ++foobar } \
END { print "'"'"'foo'"' appears " foobar " times." }'"' BBS.txt"
awk 'BEGIN { print "Analysis of ‘foo’" }
/foo/ { ++foobar }
END { print "‘foo’ appears " foobar " times." }' BBS.txt
printf "awk '{ print \$1 }' BBS.txt\n"
awk '{ print $1 }' BBS.txt
