#!/usr/bin/env bash
println() {
  printf '%s\n' "$*"
}
println "awk '/foo/ { print \$2 }' BBS.txt"
awk '/foo/ { print $2 }' BBS.txt
println "awk '\$1 ~ /J/' inventory.txt"
awk '$1 ~ /J/' inventory.txt
println "awk '{ if (\$1 ~ /J/) print }' inventory.txt"
awk '{ if ($1 ~ /J/) print }' inventory.txt
println "awk '\$1 !~ /J/' inventory.txt"
awk '$1 !~ /J/' inventory.txt
println "awk 'tolower(\$1) ~ /foo/ { print }' BBS.txt"
awk 'tolower($1) ~ /foo/ { print }' BBS.txt
println "awk \$1 == \"foo\" { print \$2 }' BBS.txt"
awk '$1 == "foo" { print $2 }' BBS.txt
println "awk \$1 ~ \"foo\" { print \$2 }' BBS.txt"
awk '$1 ~ "foo" { print $2 }' BBS.txt
println "awk '\$1 ~ /foo/ { print \$2 }' BBS.txt"
awk '$1 ~ /foo/ { print $2 }' BBS.txt
println "awk '/2400/ && /foo/' BBS.txt"
awk '/2400/ && /foo/' BBS.txt
println "awk '/2400/ || /foo/' BBS.txt"
awk '/2400/ || /foo/' BBS.txt
println "awk '! /foo/' BBS.txt"
awk '! /foo/' BBS.txt
println "awk 'BEGIN { print \"Analysis of foo\" } \
/foo/ { ++foobar } \
END { print \"foo\" appears \" foobar \" times.\" }' BBS.txt"
awk 'BEGIN { print "Analysis of foo" }
/foo/ { ++foobar }
END { print "foo appears " foobar " times." }' BBS.txt
println "awk '{ print \$1 }' BBS.txt"
awk '{ print $1 }' BBS.txt
