#!/usr/bin/env bash
echo "awk 'BEGIN { print "'"line one\nline two\nline three"'" }'"
awk 'BEGIN { print "line one\nline two\nline three" }'
echo "awk '{ print "'$1, $2'" }' inventory.txt"
awk '{ print $1, $2 }' inventory.txt
echo "awk 'BEGIN { print "'"Month Crates"'" \
print "'"----- ------"'" } \
{ print "'$1, $2'" }' inventory.txt"
awk 'BEGIN { print "Month Crates"
print "----- ------" }
{ print $1, $2 }' inventory.txt
echo "awk 'BEGIN { print "'"Month Crates"'" \
print "'"----- ------"'" } \
{ print "'$1, " ", $2'" }' inventory.txt"
awk 'BEGIN { print "Month Crates"
print "----- ------" }
{ print $1, " ", $2 }' inventory.txt
echo "awk 'BEGIN { OFS = "'";"'"; ORS = "'"\n\n"'" } \
{ print "'$1, $2'" }' BBS.txt"
awk 'BEGIN { OFS = ";"; ORS = "\n\n" }
{ print $1, $2 }' BBS.txt
