#!/usr/bin/env bash
println() {
  printf '%s\n' "$*"
}
cat BBS.txt
println "awk 'BEGIN { RS = \"/\" } ; { print \$0 }' BBS.txt"
awk 'BEGIN { RS = "/" } ; { print $0 }' BBS.txt
println "awk '{ print \$0 }' RS=\"/\" BBS.txt"
awk '{ print $0 }' RS="/" BBS.txt
println "awk '{ print \$0 }' RS=\"\" BBS.txt"
awk '{ print $0 }' RS="" BBS.txt
